# Generated by Django 6.1.1 on 2026-10-01 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Mascota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=60)),
                ("raza", models.CharField(blank=True, max_length=60)),
                ("edad", models.PositiveSmallIntegerField(help_text="Edad en años")),
                ("descripcion", models.TextField(blank=True)),
                (
                    "imagen",
                    models.URLField(
                        help_text="URL de una foto de la mascota", max_length=500
                    ),
                ),
                ("disponible", models.BooleanField(default=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mascotas",
                        to="mascotas.categoria",
                    ),
                ),
            ],
            options={
                "ordering": ["-disponible", "nombre"],
            },
        ),
    ]
